// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuanLyKhoApi.Data;

#nullable disable

namespace QuanLyKhoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251007070640_AddFieldHinh")]
    partial class AddFieldHinh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClaimsRole", b =>
                {
                    b.Property<int>("ClaimsId")
                        .HasColumnType("integer");

                    b.Property<string>("RolesId")
                        .HasColumnType("text");

                    b.HasKey("ClaimsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("ClaimsRole");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ChiTietNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric");

                    b.Property<string>("MaHH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaHH");

                    b.ToTable("ChiTietNhap");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ChiTietXuat", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhieuXuat"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric");

                    b.Property<string>("MaHH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("MaPhieuXuat");

                    b.HasIndex("MaHH");

                    b.ToTable("ChiTietXuat");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.Claims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Quyen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ComfirmAccount", b =>
                {
                    b.Property<Guid>("IdTaiKhoan")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdTaiKhoan");

                    b.ToTable("ComfirmAccounts");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.HangHoa", b =>
                {
                    b.Property<string>("MaHH")
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("numeric");

                    b.Property<int>("IdLoai")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("integer");

                    b.Property<string>("TenHH")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MaHH");

                    b.HasIndex("IdLoai");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.HinhAnhHH", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaHH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaHH");

                    b.ToTable("HinhAnhHH");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.Loai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Loai");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.NhaCungCap", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("text");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.NhanVien", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlHinh")
                        .HasColumnType("text");

                    b.Property<string>("chucVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("diaChi")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gioiTinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ngaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("trangthai")
                        .HasColumnType("boolean");

                    b.HasKey("IdNhanVien");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MaNV")
                        .HasColumnType("uuid");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.PhieuXuat", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhieuXuat"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<Guid>("MaNV")
                        .HasColumnType("uuid");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaPhieuXuat");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("PhieuXuat");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.RoleClaim", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoan", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdNhanVien");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoanRole", b =>
                {
                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("TaiKhoanId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("TaiKhoanRoles");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoanToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdTaiKhoan")
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("TaiKhoanToken");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TrangThaiPhieu", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTrangThai"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MaTrangThai");

                    b.ToTable("TrangThaiPhieu");
                });

            modelBuilder.Entity("ClaimsRole", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.Claims", null)
                        .WithMany()
                        .HasForeignKey("ClaimsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ChiTietNhap", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ChiTietXuat", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ComfirmAccount", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.TaiKhoan", "TaiKhoan")
                        .WithOne("ComfirmAccount")
                        .HasForeignKey("QuanLyKhoApi.Data.ComfirmAccount", "IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.HangHoa", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.Loai", "loai")
                        .WithMany()
                        .HasForeignKey("IdLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("loai");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.HinhAnhHH", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.HangHoa", "HangHoa")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.TrangThaiPhieu", "TrangThaiPhieu")
                        .WithMany()
                        .HasForeignKey("MaTrangThai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("TrangThaiPhieu");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.PhieuXuat", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.TrangThaiPhieu", "TrangThaiPhieu")
                        .WithMany()
                        .HasForeignKey("MaTrangThai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("TrangThaiPhieu");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.RoleClaim", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.Claims", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QuanLyKhoApi.Data.TaiKhoan", "IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoanRole", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.Role", "Role")
                        .WithMany("TaiKhoanRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.TaiKhoan", "TaiKhoan")
                        .WithMany("TaiKhoanRoles")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoanToken", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.TaiKhoan", "TaiKhoan")
                        .WithMany("TaiKhoanTokens")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.HangHoa", b =>
                {
                    b.Navigation("HinhAnhs");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.NhanVien", b =>
                {
                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.Role", b =>
                {
                    b.Navigation("TaiKhoanRoles");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoan", b =>
                {
                    b.Navigation("ComfirmAccount");

                    b.Navigation("TaiKhoanRoles");

                    b.Navigation("TaiKhoanTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
