// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuanLyKhoApi.Data;

#nullable disable

namespace QuanLyKhoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019083517_Update_ThongKe")]
    partial class Update_ThongKe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhoApi.Data.CauHinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MaHH")
                        .HasColumnType("uuid");

                    b.Property<string>("MauSac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("Ram")
                        .HasColumnType("text");

                    b.Property<string>("Rom")
                        .HasColumnType("text");

                    b.Property<int?>("SoLuongHidden")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaHH");

                    b.ToTable("CauHinh");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ChiTietNhap", b =>
                {
                    b.Property<int>("MaChiTietNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChiTietNhap"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MaCauHinh")
                        .HasColumnType("uuid");

                    b.Property<int?>("PhieuNhapMaPhieuNhap")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("MaChiTietNhap");

                    b.HasIndex("MaCauHinh");

                    b.HasIndex("PhieuNhapMaPhieuNhap");

                    b.ToTable("ChiTietNhap");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ChiTietXuat", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhieuXuat"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MaCauHinh")
                        .HasColumnType("uuid");

                    b.Property<int?>("PhieuXuatMaPhieuXuat")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("MaPhieuXuat");

                    b.HasIndex("MaCauHinh");

                    b.HasIndex("PhieuXuatMaPhieuXuat");

                    b.ToTable("ChiTietXuat");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.Claims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Quyen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Quyen = "User"
                        },
                        new
                        {
                            Id = 2,
                            Quyen = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Category = "NhanVien",
                            Quyen = "ThemNhanVien"
                        },
                        new
                        {
                            Id = 4,
                            Category = "NhanVien",
                            Quyen = "XoaNhanVien"
                        },
                        new
                        {
                            Id = 5,
                            Category = "NhanVien",
                            Quyen = "SuaNhanVien"
                        },
                        new
                        {
                            Id = 6,
                            Category = "NhanVien",
                            Quyen = "XemNhanVien"
                        },
                        new
                        {
                            Id = 7,
                            Category = "NhaCungCap",
                            Quyen = "ThemNhaCungCap"
                        },
                        new
                        {
                            Id = 8,
                            Category = "NhaCungCap",
                            Quyen = "XoaNhaCungCap"
                        },
                        new
                        {
                            Id = 9,
                            Category = "NhaCungCap",
                            Quyen = "SuaNhaCungCap"
                        },
                        new
                        {
                            Id = 10,
                            Category = "NhaCungCap",
                            Quyen = "XemNhaCungCap"
                        },
                        new
                        {
                            Id = 11,
                            Category = "HangHoa",
                            Quyen = "ThemHangHoa"
                        },
                        new
                        {
                            Id = 12,
                            Category = "HangHoa",
                            Quyen = "XoaHangHoa"
                        },
                        new
                        {
                            Id = 13,
                            Category = "HangHoa",
                            Quyen = "SuaHangHoa"
                        },
                        new
                        {
                            Id = 14,
                            Category = "HangHoa",
                            Quyen = "XemHangHoa"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Loai",
                            Quyen = "ThemLoai"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Loai",
                            Quyen = "XoaLoai"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Loai",
                            Quyen = "SuaLoai"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Loai",
                            Quyen = "XemLoai"
                        },
                        new
                        {
                            Id = 19,
                            Category = "ThongKe",
                            Quyen = "XemThongKe"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Role",
                            Quyen = "ThemRole"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Role",
                            Quyen = "XoaRole"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Role",
                            Quyen = "SuaRole"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Role",
                            Quyen = "XemRole"
                        },
                        new
                        {
                            Id = 24,
                            Category = "PhieuNhap",
                            Quyen = "ThemPhieuNhap"
                        },
                        new
                        {
                            Id = 25,
                            Category = "PhieuNhap",
                            Quyen = "XemPhieuNhap"
                        },
                        new
                        {
                            Id = 26,
                            Category = "PhieuXuat",
                            Quyen = "ThemPhieuXuat"
                        },
                        new
                        {
                            Id = 27,
                            Category = "PhieuXuat",
                            Quyen = "XemPhieuXuat"
                        },
                        new
                        {
                            Id = 28,
                            Category = "TaiKhoan",
                            Quyen = "ThemTaiKhoan"
                        },
                        new
                        {
                            Id = 29,
                            Category = "TaiKhoan",
                            Quyen = "XoaTaiKhoan"
                        },
                        new
                        {
                            Id = 30,
                            Category = "TaiKhoan",
                            Quyen = "SuaTaiKhoan"
                        },
                        new
                        {
                            Id = 31,
                            Category = "TaiKhoan",
                            Quyen = "XemTaiKhoan"
                        });
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ComfirmAccount", b =>
                {
                    b.Property<Guid>("IdTaiKhoan")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdTaiKhoan");

                    b.ToTable("ComfirmAccounts");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.HangHoa", b =>
                {
                    b.Property<Guid>("MaHH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("IdLoai")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NhaCungCapId")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("integer");

                    b.HasKey("MaHH");

                    b.HasIndex("IdLoai");

                    b.HasIndex("NhaCungCapId");

                    b.ToTable("HangHoa");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.HinhAnhHH", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CauHinhId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Stt")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CauHinhId");

                    b.ToTable("HinhAnhHH");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.Loai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Loai");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.NhaCungCap", b =>
                {
                    b.Property<int>("MaNCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNCC"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, object>>("DiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("text");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.NhanVien", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlHinh")
                        .HasColumnType("text");

                    b.Property<string>("chucVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, object>>("diaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gioiTinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ngaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("trangthai")
                        .HasColumnType("boolean");

                    b.HasKey("IdNhanVien");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.PhieuNhap", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MaHH")
                        .HasColumnType("uuid");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MaNV")
                        .HasColumnType("uuid");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaHH");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.PhieuXuat", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaPhieuXuat"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<decimal?>("GiaXuat")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MaHH")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaNV")
                        .HasColumnType("uuid");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaPhieuXuat");

                    b.HasIndex("MaHH");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("PhieuXuat");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = "user",
                            Deleted = false,
                            VaiTro = "User"
                        },
                        new
                        {
                            Id = "admin",
                            Deleted = false,
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.RoleClaim", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("RoleClaims");

                    b.HasData(
                        new
                        {
                            RoleId = "user",
                            ClaimId = 1
                        },
                        new
                        {
                            RoleId = "admin",
                            ClaimId = 2
                        });
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoan", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdNhanVien");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoanRole", b =>
                {
                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("TaiKhoanId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("TaiKhoanRoles");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoanToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdTaiKhoan")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("TaiKhoanToken");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ThongKe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("SoPhieuluongNhap")
                        .HasColumnType("integer");

                    b.Property<int>("SoPhieuluongXuat")
                        .HasColumnType("integer");

                    b.Property<decimal>("TongGiaNhap")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TongGiaXuat")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ThongKe");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TrangThaiPhieu", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTrangThai"));

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MaTrangThai");

                    b.ToTable("TrangThaiPhieu");

                    b.HasData(
                        new
                        {
                            MaTrangThai = 1,
                            TenTrangThai = "Đang xử lý"
                        },
                        new
                        {
                            MaTrangThai = 2,
                            TenTrangThai = "Hoàn thành"
                        },
                        new
                        {
                            MaTrangThai = 3,
                            TenTrangThai = "Hủy"
                        });
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.CauHinh", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.HangHoa", "HangHoa")
                        .WithMany("CauHinhs")
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ChiTietNhap", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.CauHinh", "CauHinh")
                        .WithMany()
                        .HasForeignKey("MaCauHinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.PhieuNhap", null)
                        .WithMany("ChiTietNhaps")
                        .HasForeignKey("PhieuNhapMaPhieuNhap");

                    b.Navigation("CauHinh");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ChiTietXuat", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.CauHinh", "CauHinh")
                        .WithMany()
                        .HasForeignKey("MaCauHinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.PhieuXuat", null)
                        .WithMany("ChiTietXuats")
                        .HasForeignKey("PhieuXuatMaPhieuXuat");

                    b.Navigation("CauHinh");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.ComfirmAccount", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.TaiKhoan", "TaiKhoan")
                        .WithOne("ComfirmAccount")
                        .HasForeignKey("QuanLyKhoApi.Data.ComfirmAccount", "IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.HangHoa", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.Loai", "loai")
                        .WithMany()
                        .HasForeignKey("IdLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("loai");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.HinhAnhHH", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.CauHinh", "CauHinh")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("CauHinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHinh");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.TrangThaiPhieu", "TrangThaiPhieu")
                        .WithMany()
                        .HasForeignKey("MaTrangThai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("NhanVien");

                    b.Navigation("TrangThaiPhieu");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.PhieuXuat", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.HangHoa", "HangHoa")
                        .WithMany()
                        .HasForeignKey("MaHH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.TrangThaiPhieu", "TrangThaiPhieu")
                        .WithMany()
                        .HasForeignKey("MaTrangThai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangHoa");

                    b.Navigation("NhanVien");

                    b.Navigation("TrangThaiPhieu");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.RoleClaim", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.Claims", "Claim")
                        .WithMany("RoleClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QuanLyKhoApi.Data.TaiKhoan", "IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoanRole", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.Role", "Role")
                        .WithMany("TaiKhoanRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhoApi.Data.TaiKhoan", "TaiKhoan")
                        .WithMany("TaiKhoanRoles")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoanToken", b =>
                {
                    b.HasOne("QuanLyKhoApi.Data.TaiKhoan", "TaiKhoan")
                        .WithMany("TaiKhoanTokens")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.CauHinh", b =>
                {
                    b.Navigation("HinhAnhs");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.Claims", b =>
                {
                    b.Navigation("RoleClaims");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.HangHoa", b =>
                {
                    b.Navigation("CauHinhs");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.NhanVien", b =>
                {
                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietNhaps");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietXuats");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("TaiKhoanRoles");
                });

            modelBuilder.Entity("QuanLyKhoApi.Data.TaiKhoan", b =>
                {
                    b.Navigation("ComfirmAccount");

                    b.Navigation("TaiKhoanRoles");

                    b.Navigation("TaiKhoanTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
